version: '3'
networks:
        my-network:

services:
  elasticsearch:
    image: elasticsearch:5.3.0
    ports:
      - "9200:9200"
    networks:
      - my-network

  kibana:
    image: kibana:5.3.0
    depends_on:
      - elasticsearch

    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - my-network

  fluentd:
    build: ./fluentd
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
    networks:
      - my-network

  web:
    build: ./nginx
    ports:
      - "8058:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx
    networks:
      - my-network

